# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/calibrate-simulation',
                'doc_host': 'https://valueanalyticslabs.github.io',
                'git_url': 'https://github.com/valueanalyticslabs/calibrate-simulation',
                'lib_path': 'calibrate_simulation'},
  'syms': {'calibrate_simulation\\core': {'calibrate_simulation\\core.foo': ('core.html#foo', 'calibrate_simulation\\core.py')}}}